src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
  /**
   * @ORM\Id
   * @ORM\GeneratedValue
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $author;

  /**
   * @ORM\Column(type="date", nullable=true)
   */
  private $date_publish;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $summary;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getAuthor(): ?string
  {
    return $this->author;
  }

  public function setAuthor(string $author): self
  {
    $this->author = $author;

    return $this;
  }

  public function getDatePublish(): ?\DateTimeInterface
  {
    return $this->date_publish;
  }

  public function setDatePublish(?\DateTimeInterface $date_publish): self
  {
    $this->date_publish = $date_publish;

    return $this;
  }

  public function getSummary(): ?string
  {
    return $this->summary;
  }

  public function setSummary(?string $summary): self
  {
    $this->summary = $summary;

    return $this;
  }
}

src/Controller/LearnController.php
<?php

namespace App\Controller;


use App\Entity\Book;
use App\Repository\BookRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LearnController extends AbstractController
{
  /**
   * @Route("/learn", name="learn_index", methods={"GET"})
   */
  public function index(BookRepository $bookRepository): Response
  {
    $books = $bookRepository->findAll();

    return $this->render('learn/index.html.twig', [
      'books' => $books,
    ]);
  }


  /**
   * @Route("/learn/tutorials", name="learn_tutorials", methods={"GET"})
   */
  public function tutorials(): Response
  {
    return $this->render('learn/tutorials.html.twig', [
      'test' => 'Vous êtes sur la page des tutoriels'
    ]);
  }


  /**
   * @Route("/learn/books", name="learn_books", methods={"GET"})
   */
  public function books(BookRepository $bookRepository, Request $request): Response
  {
    // ici on récupère le contenu de $_GET
    $action = $request->query->get('action');
    $method = $request->getMethod();

    $books = $bookRepository->findAll();

    return $this->render('learn/books.html.twig', [
      'books' => $books,
      'method' => $method,
      'action' => $action,
    ]);
  }

  /**
   * @Route("/learn/books/{id}", name="learn_books_detail", methods={"GET"})
   *
   * @param Book $book
   * @return Response
   */
  public function books_detail(Book $book): Response
  {
    return $this->render('learn/books_detail.html.twig', [
      'book' => $book
    ]);
  }
}

templates/learn/_learn_navigation.html.twig
<div class="row mb-2">
  <div class="col bg-warning p-2">
    <a class="btn btn-outline-primary" href="{{ path('learn_index') }}">Accueil</a>
    <a class="btn btn-outline-primary" href="{{ path('learn_tutorials') }}">Tutoriels</a>
    <a class="btn btn-outline-primary" href="{{ path('learn_books')}}">Livres</a>
  </div>
</div>

templates/learn/books.html.twig
{% extends "base.html.twig" %}

{% block title %}Learn | Livres{% endblock %}




{% block body %}
  
  {% include "learn/_learn_navigation.html.twig" %}

  <p class="text-danger">La méthode de la requête est {{ method }}</p>
  <p class="text-danger">La valeur de $_GET['action'] est {{ action }}</p>

  <h1>Livres</h1>

  <div class="row">
    {% for book in books %}
      <div class="col-4">
        <div class="card px-2 py-3 mb-2">
          <h5 class="bg-hero text-light p-1 rounded rounded-3">{{ book.title }}</h5>
          <h6 class="text-secondary text-end">{{ book.author }}</h6>
          <p>{{ book.summary }}</p>
          <p>{{ book.datePublish | date('d/m/Y') }}</p>
          <a href="/learn/books/{{book.id}}">Voir plus...</a>
        </div>
      </div>
    {% endfor %}
  </div>


{% endblock %}

templates/learn/books_detail.html.twig
{% extends "base.html.twig" %}

{% block title %}Learn | Détail Livre {{ book.id }}{% endblock %}




{% block body %}
  
  {% include "learn/_learn_navigation.html.twig" %}

  <h1 class="text-hero">{{ book.title }}</h1>

  <img class="writer-image" src="{{asset('img/writer.png')}}" alt="">
  <h5>{{ book.author }}</h5>

  <p>{{ book.summary }}</p>


{% endblock %}

templates/learn/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Learn | Home{% endblock %}

{% block body %}

  {# Learn Navigation Bar #}
  {{ include('learn/_learn_navigation.html.twig') }}

  <h1 class="mb-5">Apprendre le Développement Web</h1>

  <h5>Liste des ouvrages disponibles</h5>

  <ul>
    {% for book in books %}
      <li>{{ book.title }}</li>      
    {% endfor %}
  </ul>

{% endblock %}

templates/learn/tutorials.html.twig
{% extends "base.html.twig" %}

{% block title %}Learn | Tutoriels{% endblock %}




{% block body %}
  
  {% include "learn/_learn_navigation.html.twig" %}

  <h1>Tutoriels</h1>

  <p>{{ test }}</p>

{% endblock %}