src/Entity/Person.php
<?php

namespace App\Entity;

use App\Repository\PersonRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 */
class Person
{
  /**
   * @ORM\Id
   * @ORM\GeneratedValue
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   * @Assert\Length(
   *    min = 3,
   *    max = 30,
   *    minMessage = "Ce champ doit contenir au moins {{ limit }} charactères",
   *    maxMessage = "Ce champ doit contenir maximum {{ limit }} charactères"
   * )
   */
  private $ls_name;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   * @Assert\Length(
   *    min = 3,
   *    max = 30,
   *    minMessage = "Ce champ doit contenir au moins {{ limit }} charactères",
   *    maxMessage = "Ce champ doit contenir maximum {{ limit }} charactères"
   * )
   */
  private $fs_name;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $notes;

  /**
   * @ORM\Column(type="boolean")
   */
  private $confirmed;

  /**
   * @ORM\Column(type="string", length=100, nullable=true)
   * @Assert\Email(
   *    message = "{{ value }} n'est pas une adresse mail valide"
   * )
   */
  private $email;

  /**
   * @ORM\ManyToOne(targetEntity=Team::class, inversedBy="persons")
   */
  private $team;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getLsName(): ?string
  {
    return $this->ls_name;
  }

  public function setLsName(string $ls_name): self
  {
    $this->ls_name = $ls_name;

    return $this;
  }

  public function getFsName(): ?string
  {
    return $this->fs_name;
  }

  public function setFsName(?string $fs_name): self
  {
    $this->fs_name = $fs_name;

    return $this;
  }

  public function getNotes(): ?string
  {
    return $this->notes;
  }

  public function setNotes(?string $notes): self
  {
    $this->notes = $notes;

    return $this;
  }

  public function getConfirmed(): ?bool
  {
    return $this->confirmed;
  }

  public function setConfirmed(bool $confirmed): self
  {
    $this->confirmed = $confirmed;

    return $this;
  }

  public function getEmail(): ?string
  {
    return $this->email;
  }

  public function setEmail(?string $email): self
  {
    $this->email = $email;

    return $this;
  }

  public function getTeam(): ?Team
  {
      return $this->team;
  }

  public function setTeam(?Team $team): self
  {
      $this->team = $team;

      return $this;
  }
}

src/Controller/BackController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Entity\Person;

use App\Form\TeamType;
use App\Form\PersonType;


use App\Repository\PersonRepository;
use App\Repository\TeamRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class BackController extends AbstractController
{
  /**
   * @Route("/back", name="back_index", methods={"GET"})
   */
  public function index(): Response
  {
    return $this->render('back/index.html.twig', [
      'controller_name' => 'BackController',
    ]);
  }

  /**
   * @Route("/team", name="back_team", methods={"GET", "POST"})
   */
  public function teamShowAll(TeamRepository $teamRepo, PersonRepository $personRepo, Request $request, EntityManagerInterface $em): Response
  {

    $team = new Team();
    // on affecte la valeur de '$members' en allant compter le nb de personnes reliées au team
    $team->setMembers(count($team->getPersons()));

    $form = $this->createForm(TeamType::class, $team);

    $form->handleRequest($request);

    // ### traitement de formulaire
    if ($form->isSubmitted() && $form->isValid()) {
      $em->persist($team);
      $em->flush();

      $this->redirectToRoute('back_team');
    }

    /**
     * on met à jour les compteurs des membres
     */

    $teams = $teamRepo->findAll();

    // $counter = [];
    foreach ($teams as $team) {
      // $counter[$team->getId()] = count($personRepo->findBy(['team' => $team->getId()]));

      /**
       * À chaque fois que cette page est affichée,
       * on met à jour les compteurs dans la BDD
       */
      // $team->setMembers(count($personRepo->findBy(['team' => $team->getId()])));
      // $em->flush();
    }

    return $this->render('back/team.html.twig', [
      'teams' => $teams,
      'form' => $form->createView(),
      // 'counter' => $counter,
    ]);
  }

  //
  /**
   * @Route("/person", name="back_person", methods={"GET"})
   */
  public function personShowAll(PersonRepository $personRepository): Response
  {
    // $persons = $personRepository->findAll();
    $persons = $personRepository->findAllOrderByTeam();

    return $this->render('back/person.html.twig', [
      'persons' => $persons
    ]);
  }


  // MK -- Ici création & modification par une même action, avec ou sans {id}
  /**
   * @Route("/back/person/add", name="back_person_add", methods={"GET", "POST"})
   * @Route("/back/person/edit/{id}", name="back_person_edit", methods={"GET", "POST"})
   */
  public function personAdd(Person $person = null, Request $request, EntityManagerInterface $manager)
  {
    /**
     * 1. 
     *    Si c'est une création on crée une nouvelle instance (car $person = null)
     *    Si c'est une modification $person contient déjà les données
     */
    if (!$person) {
      $person = new Person();
    }

    // 2. on la passe en 2e argument au formulaire,
    // qui va automatiquement mapper les champs de f. avec les propriétés de l'objet
    $form = $this->createForm(PersonType::class, $person);

    // MK -- NOTE
    /**
     * Si on voulait changer les valeurs de 'method' & 'action' on pourrait passer des options:
     * 
     * $form = $this->createForm(PersonType::class, $person, [
     *    'action' => $this->generateUrl('target_route),
     *    'method' => 'GET'
     * ])
     */

    $form->handleRequest($request);

    // 3. On traite le formulaire
    if ($form->isSubmitted() && $form->isValid()) {
      // traitement de formulaire...

      /**
       * 4.
       *    Si c'est une création $personne ne contient pas encore d'id et on doit persister la nouvelle instance
       *    Si c'est une modification on peut lire la p. $id
       */

      if (!$person->getId()) {
        $manager->persist($person);
      }

      $manager->flush();
      return $this->redirectToRoute('back_person');
    }

    // 4. On pass le formulaire à la vue
    return $this->render('back/person_add.html.twig', [
      'form' => $form->createView()
    ]);
  }
}


/**
 * Argument 1 passed to Doctrine\ORM\Persisters\Entity\BasicEntityPersister::getSelectConditionStatementColumnSQL() 
 * 
 * must be of the type string, 
 * 
 * int given, called in /Applications/MAMP/htdocs/symfony22/udes/blog/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php on line 1627
 */

templates/back/_back_navigation.html.twig
<div class="row mb-2">
  <div class="col bg-secondary p-2">
    <a class="btn btn-outline-light" href="{{ path('back_index') }}">Back</a>
    <a class="btn btn-outline-light" href="{{ path('back_team') }}">Teams</a>
    <a class="btn btn-outline-light" href="{{ path('back_person') }}">Personnes</a>
    <a class="btn btn-outline-light" href="{{ path('back_person_add') }}">Ajouter Personne</a>

  </div>
</div>

templates/back/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Back Office{% endblock %}

{% block body %}

  {{ include('back/_back_navigation.html.twig') }}


  {% block back_content %}

    <h4>Accueil du Back Office</h4>

    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci, amet! Cupiditate veniam, mollitia vel cum ratione in accusamus vero voluptatibus id tempore laborum illo nobis explicabo recusandae, assumenda eum blanditiis.</p>

  {% endblock %}

  

{% endblock %}

templates/back/person.html.twig
{% extends "back/index.html.twig" %}

{% block title %}Liste Personne{% endblock %}

{% block back_content %}

  <h4>Liste des personnes</h4>


  <div class="row">
    {% for p in persons %}

      <div class="col-4 mb-2">
        <div class="card p-2">
          <small class="text-secondary fw-bold fs-3">{{ p.id }}</small>
          <h4>{{ p.lsName ~ ' ' ~ p.fsName }}</h4>
          <h5 class="text-info">{{ p.team }}</h5>
          <p>{{ p.notes }}</p>

            {% if p.confirmed %} 
              <p><span class="badge rounded-pill bg-success">Confirmé</span></p>
            {% else %}
              <p><span class="badge rounded-pill bg-warning text-dark">En attente</span></p>
              
            {% endif %}

            <a href="{{ path("back_person_edit", { 'id': p.id }) }}" class="btn btn-outline-warning w-50 mb-2">Modifier</a>
            <a href="#" class="btn btn-outline-danger w-50 mb-2">Supprimer</a>

        </div>
      </div>

    {% endfor %}
  </div>


{% endblock %}

templates/back/person_add.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajout Personne{% endblock %}

{% block body %}
  {{ include('back/_back_navigation.html.twig') }}

  {{ form_start(form) }}

    {# A*A -- LS_NAME  #}
    <div class="mb-2">
      {{ form_label(form.ls_name, 'Nom de famille', { 'label_attr' : { 'class': 'form-label text-secondary' }}) }}
      {{ form_widget(form.ls_name, { 'attr' : { 'class': 'form-control' }}) }}

      <div class="text-danger">
        {{ form_errors(form.ls_name) }}
      </div>
    </div>

    {# A*A -- FS_NAME #}
    <div class="mb-2">
      {{ form_label(form.fs_name, 'Prénom', { 'label_attr' : { 'class': 'form-label text-secondary' }}) }}
      {{ form_widget(form.fs_name, { 'attr' : { 'class': 'form-control' }}) }}

      <div class="text-danger">
        {{ form_errors(form.fs_name) }}
      </div>
    </div>

    {# A*A -- EMAIL #}
    <div class="mb-2">
      {{ form_label(form.email, 'Adresse Mail', { 'label_attr': { 'class': 'form-label text-secondary'}}) }}
      {{ form_widget(form.email, { 'attr': { 'class': 'form-control' }}) }}

      {{ form_help(form.email) }}

      <div class="text-danger">
        {{ form_errors(form.email) }}
      </div>
    </div>

    {# A*A -- NOTES #}  
    <div class="mb-2">
      {{ form_label(form.notes, 'Précisions', { 'label_attr' : { 'class': 'form-label text-secondary' }}) }}
      {{ form_widget(form.notes, { 'attr' : { 'class': 'form-control' }}) }}  
    </div>

    {# A*A -- CONFIRMED #}
    <div class="mb-2">
      {{ form_widget(form.confirmed, { 'attr' : { 'class': 'form-check-input' }}) }}  
      {{ form_label(form.confirmed, 'Confirmé', { 'label_attr' : { 'class': 'form-label' }}) }}
    </div>

    {# A*A -- ENREGISTRER #}
    <div class="mb-2">
      {{ form_widget(form.Enregistrer, { 'attr' : { 'class': 'btn btn-info text-light' }}) }}  
    </div>




    {# Le reste du formulaire #}
    {{ form_rest(form) }}

  {{ form_end(form) }}

{% endblock %}

templates/back/team.html.twig
{% extends "back/index.html.twig" %}

{% block title %}Back | Teams{% endblock %}

{% block back_content %}

  <h4>Teams disponibles</h4>

  {% for t in teams %}
    <div class="row mb-2">
      <div class="col card p-2">
        {# <h1>{{ t.id ~ ' - ' ~ t.name ~ '(' ~ counter[t.id] ~ ')' }}</h1> #}
        
        <p class="fs-3">
          <span class="team-badge" style="background-color: {{ t.color }}"></span>
          {{ t.id ~ ' - ' ~ t.name ~ ' (' ~ t.persons | length ~ ')' }}
        </p>

      </div>
    </div>
  {% endfor %}

  <hr>

  {{ form_start(form) }}

  {{ form_end(form) }}




{% endblock %}